### ISSUE TITLE
Building the project

### ISSUE THREAD

**Issue by ericdes** [gautamsi/winjs-node#1]
I would like to know how to build your project, I'm not familiar with grunt. 
Thank you!

**Comment by gautamsi** [comment]
Don't worry about building right now. I was not able to clean all the files from original WinJS. This is CmmonJS module in Node. use NPM to install winjs-node module (https://www.npmjs.com/package/winjs-node) the goal was to use same winjs api for my other library. When using requirejs or browser based script, I just use official WinJS

If you are making any changes to .ts files, make sure you have TypeScript compile on save turned on. Or just run tsc in in the node enabled command prompt when you are in the root folder.

**Comment by ericdes** [comment]
I put in my starting html file:

```
    <!-- WinJS-Node references -->    
    <script src="node_modules/winjs-node/src/js/WinJS/Core.js"></script>
    <script src="node_modules/winjs-node/src/js/WinJS/Promise.js"></script>
    <script src="node_modules/winjs-node/src/js/WinJS/Scheduler.js"></script>
    <script src="node_modules/winjs-node/src/js/WinJS/Utilities.js"></script>
    <script src="node_modules/winjs-node/src/js/WinJS.js"></script>
```

And I'm getting this error:
`
TS2304  Build: Cannot find name 'Promise in node_modules\winjs-node\src\js\WinJS\Scheduler.d.ts 113
`

**Comment by gautamsi** [comment]
if you are using winjs in browser based apps or in HTML files stick to official WinJS repo github/winjs/winjs or http://www.buildwinjs.com . this repo is only for node.js. You must use 

``` javascript
var WinJS = require('winjs-node'); 
```

within node.js code to load WinJS xhr and Promise.
